### ISSUE TITLE
Add a "Post-Vibe Flight Mode" 

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-c3-software#24]
On April 29th, we'll be vibration testing OreSat0.5. After that day, we may not dissemble OreSat0.5, and we may not re-stow the antennas so we're not allowed to fire the deployers. That said, we'll want to be intensively testing in "flight mode" because we'll have two weeks to do software test and fix. In those two weeks, we'll want to:

1. Never fire the deployers, ever.
2. Turn down the UHF TX AX5043 power to 0x000 (-40 dBm?) so that we don't push the power amplifier hard into the stowed antenna.

**Comment by ryanpdx** [comment]
Is this still relevant? We didn't need it for OreSat0.5

**Comment by andrewgreenberg** [comment]
No, this is no longer relevant.
