### ISSUE TITLE
Antenna deployment

### ISSUE THREAD

**Issue by andrewgreenberg** [oresat/oresat-c3-software#9]
# Monopole and Helical Antenna Deployer Testing

We can't tell if the resistor is shorted out, but we can tell if it's open. It would be nice to be able to run a test via the REST API via a button and get the ADC output and the Good/Bad decision.

* Monopole
   * Assert TEST_ANTENNAS as output high (MCASP0_AHCLKR)
   * Read READ_ANTENNAS ADC pin (AIN4)
   * Monopole deployment resistor is bad if AIN4 is > 100 mV
* Helical
   * Assert TEST_HELICAL as output high (MCASP0_FSX)
   * Read READ_HELICAL ADC pin (AIN5)
   * Helical deployment resistor is bad if AIN5 is > 100 mV

# Monopole Firing

Would be nice to have a "Deploy Monopole" button with a "yes I'm sure" checkbox or something like to make sure we don't accidentally deploy while on FlatSat.

* Assert FIRE_ANTENNAS_1 (XDMA_EVENT_INTR1) and FIRE_ANTENNAS_2 (MCASP0_AHCLKX) as output high for 10 seconds
* De-assert FIRE_ANTENNAS_1 and FIRE_ANTENNAS_2 to input floating. 

# Helical Firing

Would be nice to have a "Deploy Helical" button with a "yes I'm sure" checkbox or something like to make sure we don't accidentally deploy while on FlatSat.

* Assert FIRE_HELICAL_1 (MCASP0_AXR0) and FIRE_HELICAL_2 (MCASP0_ACLKX) as output high for 10 seconds
* De-assert FIRE_HELICAL_1 and FIRE_HELICAL_2 to input floating.

**Comment by ryanpdx** [comment]
This is done. Didn't do a webpage with nice buttons as it would have required a dedicated thread.
